FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /code
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --development -g
EXPOSE 5000
COPY . .
CMD ["npm", "run", "serve"]

# FROM node:latest as build-stage
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY ./ .
# RUN npm run build

# FROM nginx as production-stage
# RUN mkdir /app
# COPY --from=build-stage /app/dist /app
# COPY nginx.conf /etc/nginx/nginx.conf